[build]
  base = "client"
  command = "DISABLE_ESLINT_PLUGIN=true npm run build:prod"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "public" 