# fly.toml app configuration file generated for classe-numerique on 2025-08-12T22:43:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "classe-numerique"
primary_region = "cdg"

[build]

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

# Configuration pour la persistance des données
[mounts]
  source = "ecole_data"
  destination = "/app/data"

[processes]
  app = "node index.js"
